### ISSUE TITLE
PathAccessException: Directory listing failed, path = '/storage/emulated/0/Android/' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by Monday1908** [jakubslaby09/dpc#5]
```PathAccessException: Directory listing failed, path = '/storage/emulated/0/Android/' (OS Error: Permission denied, errno = 13)```
```#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42)
#1      _Directory.listSync (dart:io/directory_impl.dart:233)
#2      new CreateRepoSheet (package:dpc/widgets/create_repo_sheet.dart:8)
#3      CreateRepoSheet.show.<anonymous closure> (package:dpc/widgets/create_repo_sheet.dart:22)
#4      _BottomSheetState.build (package:flutter/src/material/bottom_sheet.dart:393)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
#69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
#72     ComponentElement.performRebuild (package:flutter/sr...
```

**Comment by Monday1908** [comment]
> ```PathAccessException: Directory listing failed, path = '/storage/emulated/0/Android/' (OS Error: Permission denied, errno = 13)```
> ```#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42)
> #1      _Directory.listSync (dart:io/directory_impl.dart:233)
> #2      new CreateRepoSheet (package:dpc/widgets/create_repo_sheet.dart:8)
> #3      CreateRepoSheet.show.<anonymous closure> (package:dpc/widgets/create_repo_sheet.dart:22)
> #4      _BottomSheetState.build (package:flutter/src/material/bottom_sheet.dart:393)
> #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
> #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
> #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> #8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> #25     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> #33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #40     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #53     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #61     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #67     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #72     ComponentElement.performRebuild (package:flutter/sr...
> ```

**Comment by jakubslaby09** [comment]
@Monday1908 Thanks for the report. I wasn't able to reproduce the error though. Could you please share a few details?
- What were you trying to do?
- What permissions did you allow/reject?
- What Android version and what device are you running on?

Thanks in advance!

**Comment by Monday1908** [comment]
> > ```PathAccessException: Directory listing failed, path = '/storage/emulated/0/Android/' (OS Error: Permission denied, errno = 13)```
> > ```#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42)
> > #1      _Directory.listSync (dart:io/directory_impl.dart:233)
> > #2      new CreateRepoSheet (package:dpc/widgets/create_repo_sheet.dart:8)
> > #3      CreateRepoSheet.show.<anonymous closure> (package:dpc/widgets/create_repo_sheet.dart:22)
> > #4      _BottomSheetState.build (package:flutter/src/material/bottom_sheet.dart:393)
> > #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
> > #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
> > #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> > #8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> > #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> > #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> > #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> > #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> > #25     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> > #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> > #33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> > #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #40     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> > #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #53     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #61     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> > #67     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> > #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> > #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> > #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> > #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> > #72     ComponentElement.performRebuild (package:flutter/sr...
> > ```
> 
>

**Comment by Monday1908** [comment]
> `PathAccessException: Directory listing failed, path = '/storage/emulated/0/Android/' (OS Error: Permission denied, errno = 13)`
> 
> ```
> #1      _Directory.listSync (dart:io/directory_impl.dart:233)
> #2      new CreateRepoSheet (package:dpc/widgets/create_repo_sheet.dart:8)
> #3      CreateRepoSheet.show.<anonymous closure> (package:dpc/widgets/create_repo_sheet.dart:22)
> #4      _BottomSheetState.build (package:flutter/src/material/bottom_sheet.dart:393)
> #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
> #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
> #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> #8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> #25     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
> #33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5634)
> #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #40     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6758)
> #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #53     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #61     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
> #67     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
> #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
> #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
> #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
> #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
> #72     ComponentElement.performRebuild (package:flutter/sr...
> ```

**Comment by jakubslaby09** [comment]
what the fuck

**Comment by Monday1908** [comment]
excuse me i'm so sorry

**Comment by jakubslaby09** [comment]
@Monday1908 It's fine, I just don't know what were you doing when re-sending, opening and closing the issue... Anyway, could you please provide some info about the error?

> - What were you trying to do?
> - What permissions did you allow/reject?
> - What Android version and what device are you running on?
